name: MentalCalc

options:
  indentWidth: 2
  tabWidth: 2

packages:
  Nimble:
    url: https://github.com/Quick/Nimble
    from: 9.2.0

targets:
  MentalCalc:
    platform: iOS
    type: application
    sources:
      - MentalCalc/
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sbs.MentalCalc
      DEVELOPMENT_TEAM: U45ZNT55FZ
    dependencies:
      - target: Multiplication
    scheme:
      testTargets:
        - MultiplicationTests
    postCompileScripts:
      - script: swiftlint
        name: Swiftlint
  Multiplication:
    platform: iOS
    type: framework
    sources: 
      - Multiplication/
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sbs.Multiplication
    scheme:
      testTargets:
        - MultiplicationTests
  MultiplicationTests:
    platform: iOS
    type: bundle.unit-test
    sources: 
      - MultiplicationTests/
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sbs.MultiplicationTests
    dependencies:
      - target: MultiplicationTests
      - package: Nimble
    scheme:
      gatherCoverageData: true